# Default values for pbw-liberty-MariaDB.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

liberty:
  enabled: true
  replicaCount: 1
  database:
    port: "3306"
    user: pbwadmin
    password: l1bertyR0cks
  image:
    name: pbw-mysql
    tag: "1.0"
    registry: "mycluster.icp:8500"
    namespace: changeme
  resources:
    limits:
      cpu: 300m
      memory: 250Mi
    requests:
      cpu: 300m
      memory: 250Mi


mariadb:
  enabled: true
  replicaCount: 1
  image:
    tag: "1.0.1"
    repository: "djccarew/mariadb-for-pbw"
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 250Mi
  database:
    user: pbwadmin
    password: l1bertyR0cks
    name: plantsdb
  service:
    port: 3306
    type: ClusterIP
