# Default values for pbw-liberty-MariaDB.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

liberty:
  enabled: true
  replicaCount: 1
  database:
    mariadbPort: 3306
    mariadbUser: pbwadmin
    mariadbPassword: l1bertyR0cks
  k8sNamespace: changeme
  image:
    name: pbw-mysql
    tag: "1.0"
  resources:
    limits:
      cpu: 300m
      memory: 250Mi
    requests:
      cpu: 300m
      memory: 250Mi


mariadb:
  enabled: true
  replicaCount: 1
  replication:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 2Gi
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 250Mi
  db:
    user: pbwadmin
    password: l1bertyR0cks
    name: plantsdb
    forcePassword: true

  service:
    port: 3306
    type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 250Mi
