apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: database

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
        tier: database

    spec:
      containers:
        - name: {{ .Release.Name }}-mariadb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name:  {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                key: maria-db-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                key: maria-db-password
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                 name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                 key: maria-db-name
