apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

type: Opaque
data:
  maria-db-user: "{{ .Values.database.mariadbUser | b64enc }}"
  maria-db-password: "{{ .Values.database.mariadbPassword | b64enc }}"
  maria-db-port: "{{ .Values.database.mariadbPort | b64enc }}"
